name: Deploy HTML Files to AppServiceCMST386
on:
  push:
    branches:
      -main
jobs:
    build-and-deploy:
      runs-on: window-latest
      steps:
      - uses: actions/checkout@master
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'CMST-Kpadill10'
          slot-name: 'production'
          publish-profile: ${{ secrets.AppServiceCMST386 }}
